-- TIENDAMATETP · Base de datos, seguridad y productos iniciales
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  category text not null check (category in ('mates','bombillas','termos','combos')),
  label text not null check (char_length(label) between 1 and 30),
  price numeric(12,2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  status text not null default 'available' check (status in ('available','low','order','out')),
  visible boolean not null default true,
  featured boolean not null default false,
  image text not null,
  description text not null default '' check (char_length(description) <= 350),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.admin_users enable row level security;
alter table public.products enable row level security;

-- Cada usuario autenticado solo puede comprobar si él mismo figura como administrador.
drop policy if exists "admin can read own permission" on public.admin_users;
create policy "admin can read own permission"
on public.admin_users for select
to authenticated
using (user_id = (select auth.uid()));

-- Visitantes: solo productos visibles. Administrador: todos.
drop policy if exists "public can read visible products" on public.products;
create policy "public can read visible products"
on public.products for select
to anon, authenticated
using (visible = true or (select public.is_admin()));

-- Solo el administrador puede modificar el catálogo.
drop policy if exists "admin can insert products" on public.products;
create policy "admin can insert products"
on public.products for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admin can update products" on public.products;
create policy "admin can update products"
on public.products for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admin can delete products" on public.products;
create policy "admin can delete products"
on public.products for delete
to authenticated
using ((select public.is_admin()));

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

-- Bucket público: cualquiera puede ver las fotos; solo el administrador puede subir/cambiar/borrar.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('product-images','product-images',true,8388608,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

drop policy if exists "admin can upload product images" on storage.objects;
create policy "admin can upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "admin can update product images" on storage.objects;
create policy "admin can update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()))
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "admin can delete product images" on storage.objects;
create policy "admin can delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()));

-- Productos de demostración. Se insertan solo si la tabla está vacía.
insert into public.products (name,category,label,price,stock,status,visible,featured,image,description)
select * from (values
('Mate Imperial Premium','mates','Mate',40000,3,'low',true,true,'assets/mate-premium-negro.png','Mate de presencia elegante, detalles metálicos y base trabajada. Ideal para quien busca un modelo protagonista.'),
('Mate Camionero','mates','Mate',35000,7,'available',true,false,'assets/mate-camionero.png','Formato camionero de madera con virola labrada. Cómodo, firme y con estilo bien argentino.'),
('Mate Calabaza con Cuero','mates','Mate',30000,4,'available',true,false,'assets/mate-calabaza.png','Calabaza natural con protector de cuero y bombilla decorada. Cada pieza presenta variaciones propias.'),
('Mate Negro Clásico','mates','Mate',25000,2,'low',true,false,'assets/mate-negro.png','Diseño sobrio en cuero negro con virola metálica y base estable.'),
('Mate Sombrero','mates','Mate',20000,0,'order',true,false,'assets/mate-sombrero.png','Mate de madera con una silueta original que recuerda al clásico sombrero criollo.'),
('Mate Coronados de Gloria','mates','Mate',30000,5,'available',true,false,'assets/mates-gloria.png','Mate de madera grabado con el Sol de Mayo. Una opción con fuerte identidad nacional.'),
('Mate de Madera','mates','Mate',22000,9,'available',true,false,'assets/mates-madera.png','Modelo de madera torneada, simple, cálido y durable para el uso de todos los días.'),
('Mate Imperial Suela','mates','Mate',38000,1,'low',true,false,'assets/mates-imperiales.png','Calabaza, virola labrada y base revestida en cuero claro con costura artesanal.'),
('Bombilla Dorada','bombillas','Bombilla',10000,12,'available',true,false,'assets/bombilla-dorada.png','Bombilla de acero con pico dorado, diseño curvo y filtro tipo paleta.'),
('Bombilla Clásica','bombillas','Bombilla',10000,18,'available',true,false,'assets/bombillas-clasicas.png','Bombilla versátil para uso diario, con filtro plano y terminación combinada.'),
('Bombilla Premium','bombillas','Bombilla',15000,6,'available',true,false,'assets/bombillas-premium.png','Modelo decorado con detalles dorados y cuerpo labrado. Terminación de estilo premium.'),
('Termo Negro Grabado','termos','Termo',45000,3,'available',true,false,'assets/termo-negro.png','Termo negro de gran capacidad con manija y grabado criollo personalizado.'),
('Combo Termo y Mate','combos','Combo',60000,2,'low',true,false,'assets/combo-termo-negro.png','Combo listo para acompañarte: termo negro, mate de calabaza, cuero y bombilla.'),
('Combo Rosa','combos','Combo',60000,0,'out',true,false,'assets/combo-rosa.png','Set rosa compuesto por termo y mate, ideal para regalo o para renovar el equipo completo.'),
('Matera Criolla Completa','combos','Matera',60000,1,'low',true,false,'assets/matera-combo.png','Matera de cuero con pelo, mate imperial y bombilla. Un conjunto de gran presencia.')
) as seed(name,category,label,price,stock,status,visible,featured,image,description)
where not exists (select 1 from public.products);

-- PASO MANUAL FINAL:
-- 1) Crear el usuario en Authentication > Users.
-- 2) Copiar su UUID y ejecutar reemplazando EL_UUID_DEL_USUARIO:
-- insert into public.admin_users (user_id) values ('EL_UUID_DEL_USUARIO');
